version: '3'
services:
  postgres:
    image: "postgres:alpine"
    labels:
      com.docker.compose.description: "Activities Site (Postgres)"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=activities_site_db"
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_USER=postgres"
  web:
    build:
      context: ./
      dockerfile: .compose/Dockerfile.cms
    command: python manage.py runserver 0.0.0.0:8000
    labels:
      com.docker.compose.description: "Activities Site (DjangoCMS)"
    ports:
      - "80:8000"
    volumes:
      - .:/usr/src/app
    links:
      - postgres
    depends_on:
      - postgres

