# Generated by Django 2.2.3 on 2019-11-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('contact_bar_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contact_bar_plugin_contact', serialize=False, to='cms.CMSPlugin'),
            preserve_default=False,
        ),
    ]
