# Generated by Django 2.2.3 on 2019-11-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('contact_bar_plugin', '0002_auto_20191120_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contact_bar_plugin_contactlist', serialize=False, to='cms.CMSPlugin')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact_bar_plugin.Contact')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
