# Generated by Django 2.2.3 on 2019-11-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('contact_bar_plugin', '0003_contactlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactList',
        ),
    ]
