# Generated by Django 2.2.3 on 2019-11-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('contact_bar_plugin', '0005_auto_20191122_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contact_bar_plugin_contact', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.DeleteModel(
            name='SocialContact',
        ),
    ]
