# Generated by Django 2.2.3 on 2019-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_bubble_plugin', '0002_auto_20191124_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
